---
name: Kivio - Blog for DevOps
owner: rollinhand
markdown: kramdown
permalink: /blog/entry/:year/:month/:day/:title
gems: 
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-sitemap
sass:
  style: compressed  

paginate: 8
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
include: ["_pages"]
---