---
name: Kivio - A practical blog for DevOps
markdown: kramdown
permalink: /entry/:year/:month/:day/:title
gems: 
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-sitemap

paginate: 10
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
include: ["_pages"]
---