---
name: Kivio - A practical blog for DevOps
markdown: kramdown
permalink: /entry/:year/:month/:day/:title
gems: [jekyll-paginate]

paginate: 10
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
---